os:
- linux
language: ruby
rvm:
- 2.2
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++6
    - fonts-droid-fallback
before_script:
- git clone https://github.com/flutter/flutter.git -b beta
- "./flutter/bin/flutter doctor"
script:
- "./flutter/bin/flutter config --enable-web"
- "./flutter/bin/flutter build web"
cache:
  directories:
  - "$HOME/.pub-cache"
before_deploy:
- rvm 2.2 do gem install aws-sdk -v 2.1.36
deploy:
  provider: s3
  access_key_id: AKIAQCNXY2QF72NAQE2V
  secret_access_key:
    secure: lsvkrhl5b5UsJD3E/U+Baq4SkNNUNU7lUfkvpY13fM/SiYfteDrlS3QRiP/sCU4sOxdJnXUcqxnC7AC8ZK98/QoSyWQw2F8CIdvgLJ+wv7b3EjniImbUMumHbaBGuE2TA7YJKphEDJPBKcIYqdcwlYJeaoLlX+ERQEaro00ij2u7nZWXapLVyrefYfpzXZ/HhogdFdhBveCk2VDS9vnGFdLdnn6z8r0aAkJcI8jBbA132i0t5kpIVIZ/2NPRrLGJrarXXe45Ai8xhhDy5k2CSJnN6hark5VIJ/4QCmrSQ44KEdaSUzrXJ7uEVyd+curiogY7viInsQfTCtKQetbjcEAq9XkLILUNATOGTRF/FTxPMPuNmSOlJqhIHTRlwLLd3OZhHqTm90fXKSs//5x9A62tq+/+UnJgG787bMPjdQs1SCFCYIFOIiPXjGSyejShHds5VGF6hJDTUs33zAlzLB+PY48zJEve/f4RWA6e+aBGzsxUbm6QKciDASujgHxY7TYNX4RvmKn1r/8NM8Jk+zy2/CwhVcEZ4xTZyCrr5G1SUrob7vItMZVCm5dU++mgotkzIdxHxLFFHDpuEv2BTndPqj4V/Dtx2/NKtpId5bBYzX38dV4tQIk3lltghwN6m+1SQfbpzmNK0zATAnSQiMPxNyrAU9JOchV0YJS1x5w=
  bucket: www.itluobo.com
  local-dir: build/web
  acl: public_read
  on:
    repo: kenvifire/blog_flutter
  skip_cleanup: 'true'
  region: us-west-2
